<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "thumbs",
                    "loop": true,
                    "keyboard": true,
                    "arrows": true,
                    "allowfullscreen": true,
                    "showCaption": true,
              
                    "transitionduration": 500,
                    "transition": "slide",
                    "navarrows": true,
                    "navtype": "thumbs",
                    "navdir": "horizontal"
                },
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
<script type="text/javascript">
    
        require(['jquery', 'mage/gallery/gallery'], function($, gallery){

        // $(".img_producto_container").ready(function() {
        //     console.log('456');
        // });


        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            $(".fotorama__stage")
            // tile mouse actions
            .on("mouseover", function() {
                    // console.log('123');
                    $(".fotorama__stage__frame")
                    .css({ transform: "scale(1.6,1.6)" });

                    $("#zoomIconContainer")
                    .css({ "display" : "flex" });

                })
            .on("mouseout", function() {
                    $(".fotorama__stage__frame")
                    .css({ transform: "scale(1,1)" });

                    $("#zoomIconContainer")
                    .css({ "display" : "none" });
                })
            .on("mousemove", function(e) {
                    $(".fotorama__stage__frame")
                    .css({
                        "transform-origin":
                        ((e.pageX - $(this).offset().left) / $(this).width()) * 100 + "% " +
                        ((e.pageY - $(this).offset().top) / $(this).height()) * 100 + "%"
                    });
                });
        });
        });

</script>